services:
  sqlite:
    image: nouchka/sqlite3
    container_name: sqlite-dev
    platform: linux/amd64
    volumes:
      - ./db:/db
      - ./schema.sql:/schema.sql
      - ./insert_data.sql:/insert_data.sql
      - ./init.sh:/init.sh
    tty: true
    entrypoint: ["/init.sh", "tail", "-f", "/dev/null"]